PuertoVaras/Controllers/HabitacionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PuertoVaras.DAL;
using PuertoVaras.Models;

namespace PuertoVaras.Controllers
{
    public class HabitacionController : Controller
    {
        private PuertoContext db = new PuertoContext();

        // GET: Habitacion
        public ActionResult Index()
        {
            this.db.Habitaciones.Add(new Habitacion
            {
                DISPONIBLE = true,
                NUMERO = 1,
                PRECIO = 222,
                TIPO_HABITACION = TipoHabitacion.Simple

            });
            this.db.SaveChanges();
            return View(db.Habitaciones.ToList());
        }

        // GET: Habitacion/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Habitacion habitacion = db.Habitaciones.Find(id);
            if (habitacion == null)
            {
                return HttpNotFound();
            }
            return View(habitacion);
        }

        // GET: Habitacion/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Habitacion/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_HABITACION,NUMERO,DISPONIBLE,TIPO_HABITACION,PRECIO")] Habitacion habitacion)
        {
            if (ModelState.IsValid)
            {
                db.Habitaciones.Add(habitacion);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(habitacion);
        }

        // GET: Habitacion/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Habitacion habitacion = db.Habitaciones.Find(id);
            if (habitacion == null)
            {
                return HttpNotFound();
            }
            return View(habitacion);
        }

        // POST: Habitacion/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_HABITACION,NUMERO,DISPONIBLE,TIPO_HABITACION,PRECIO")] Habitacion habitacion)
        {
            if (ModelState.IsValid)
            {
                db.Entry(habitacion).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(habitacion);
        }

        // GET: Habitacion/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Habitacion habitacion = db.Habitaciones.Find(id);
            if (habitacion == null)
            {
                return HttpNotFound();
            }
            return View(habitacion);
        }

        // POST: Habitacion/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Habitacion habitacion = db.Habitaciones.Find(id);
            db.Habitaciones.Remove(habitacion);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PuertoVaras/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PuertoVaras.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

PuertoVaras/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<title>Bienvenido a Puerto Varas</title>
<style>
    * {
        box-sizing: border-box;
    }

    body {
        margin: 0;
    }

    #main {
        display: flex;
        min-height: calc(100vh - 40vh);
    }

        #main > article {
            flex: 1;
        }

        #main > nav,
        #main > aside {
            flex: 0 0 20vw;
            background: beige;
        }

        #main > nav {
            order: -1;
        }

    header, footer, article, nav, aside {
        padding: 1em;
    }

    header, footer {
        background: yellowgreen;
        height: 20vh;
    }
</style>
<body>
    <div class="login-controls">
        @if (Request.IsAuthenticated)
        {
            <div>
                Hello, @System.Globalization.CultureInfo.CurrentCulture.TextInfo.ToTitleCase(User.Identity.Name).
                @Html.ActionLink("Habitaciones", "Index", "Habitacion")
                @Html.ActionLink("Clientes", "Index", "Clientes")
                @Html.ActionLink("Log Off", "LogOff", "Account")
                @Html.ActionLink("Reset Password", "ResetPassword", "Account")
            </div>
        }
        else
        {
            <div>
                @Html.ActionLink("Log In", "Login", "Account")
                @Html.ActionLink("Register", "Register", "Account")
            </div>
        }
    </div>
</body> 